### ISSUE TITLE
Add support for STORAGE_EMULATOR_HOST in gmutex

### ISSUE THREAD

**Issue by brycefisher** [ncruces/go-gcp#4]
I'd love to be able to test my code using [fake-gcs-server](https://github.com/fsouza/fake-gcs-server/tree/main), but currently there's no way to override the [hostname](https://github.com/ncruces/go-gcp/blob/master/gmutex/gmutex.go#L508) for GCS.

The [official GCS golang library](https://pkg.go.dev/cloud.google.com/go/storage#hdr-Creating_a_Client) uses the environment variable `STORAGE_EMULATOR_HOST` to allow tests to easily inject a different hostname into GCS client code. Perhaps we could follow a similar pattern in this library?

Would you be willing to review and possibly accept a PR from adding support for STORAGE_EMULATOR_HOST?

**Comment by ncruces** [comment]
Yes, sure!

**Comment by comebackoneyear** [comment]
I'm considering replacing the xml api with the [official GCS golang library](https://pkg.go.dev/cloud.google.com/go/storage#hdr-Creating_a_Client)  instead. 
Would you be interested in a PR with that?

**Comment by ncruces** [comment]
To be perfectly frank, no. And I'm not even sure that it'd work.

**Comment by ncruces** [comment]
@comebackoneyear I'd caution you into using multiple requests to implement what are supposed to be atomic operations in `gmutex`.

Your `inspectObject` is pretty bogus if you don't ensure you get the data at the same generation as you got the attributes. If it's not possible to do both in one request (I don't think it is), then a `If(storage.Conditions{GenerationMatch: …})` should fix that. Then it'd just be wasteful, but not bogus.

Doing the `extendObject` by reading it first is probably just wasteful, not wrong, but you could probably use `ComposerFrom`.

 There's also the problem of not setting `Cache-Control`, but that's less of a problem if you _never_ use public buckets.

This, by the way, is the reason I don't use the library. The [strong consistency guarantees](https://cloud.google.com/storage/docs/consistency) of GCS cover single requests, and I want to be 100% sure what requests I'm making.

**Comment by comebackoneyear** [comment]
@ncruces Thank you for your feedback! 
I was teaching myself the library and the features of gcs as I was taking a stab at this. I will take your feedback and see what I can do with it the next time I get a chance to work on it.

Currently my project using this code is passing the tests using the storage emulator which was my initial goal. It would be great if I could use the same library for production though.

Again thank you.

**Comment by ncruces** [comment]
@brycefisher I merged your PR with a few fixes. But I'm not sure there's any emulator that works with this, though.

When I started this, the JSON API was not enabled by default for all buckets. Hence I used the XML API, which is _always_ enabled. Now, the JSON is enabled by default and is the default choice by client libraries.

I could switch over; there are only 4 request types to support, after all.

It annoys me that:
- [insert](https://cloud.google.com/storage/docs/json_api/v1/objects/insert) requires multipart to send metadata and content in the same request.
- [get](https://cloud.google.com/storage/docs/json_api/v1/objects/get) can't get metadata and content in the same request.

Solutions could be:
- JSON for everything except GET
- JSON just for the emulators
- JSON is a setting
- give up because this works fine with the real deal
